[package]
name = "evm_ekubo_sdk"
version = "0.4.0"
authors = ["Mahmoud Salem <moody@ekubo.org>"]
edition = "2021"
license = "LGPL-2.1"
description = "Types for interacting with Ekubo Protocol on EVM chains"
homepage = "https://ekubo.org"
repository = "https://github.com/EkuboProtocol/evm-rust-sdk"
readme = "README.md"
keywords = ["crypto", "math", "ekubo", "protocol", "defi"]

[dependencies]
insta = "1.42.2"
num-traits = "0.2.19"
uint = "0.10.0"

[lib]
path = "src/lib.rs"
