[package]
name = "ekubo_sdk"
version = "0.1.0"
authors = ["Mahmoud Salem <moody@ekubo.org>"]
edition = "2021"


[dependencies]
num-traits = "0.2.19"
uint = "0.10.0"
thiserror = "1.0.63"

[lib]
path = "src/lib.rs"